name: "Testing"

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ["1.18", "1.19", "1.20"]
        include:
          - go: "1.18"
            analysis: true
          - go: "1.19"
            analysis: true
          - go: "1.20"
            analysis: true
    name: GO ${{ matrix.go }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go }}"

      - name: "Setup dependencies"
        run: |
          go mod download

      - name: Generate coverage report
        run: |
          go test `go list ./...` -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
